#pragma once

#define IDR_MENU 1
#define ID_FILE_SAVE 111
#define ID_FILE_EXIT 112
#define ID_VIEW_SETTINGS 121

#define IDD_DIALOG 2
#define IDC_GROUPBOX 21
#define ID_PUSHBUTTON_BG 211
#define ID_PUSHBUTTON_FONT 212
#define IDC_TEXT_FONTSIZE 221
#define IDC_TEXT_TRANSPARENCY 222
#define IDC_SLIDER_FONTSIZE 231
#define IDC_SLIDER_TRANSPARENCY 232
#define IDC_CHECKBOX_PREVIEW 24
#define ID_PUSHBUTTON_OK 251
#define ID_PUSHBUTTON_CANCEL 252

#define IDI_ICON 3
